Code refactor & Files Rename to CCS prefix
ClassicPress-research/classic-code-snippets pull request #11
Opened 2020-12-19 08:27 UTC by bahiirwa

Hoping to close issues like #8 

- Rename the prefix
- Add new plugin text domain i18n
- Fix docs and Credits and Rename plugin
- Remove unused css and html
- Prefix all functions

2020-12-19 23:51 UTC, simplycomputing reviewed
I don't really know enough to assess this. Changes to readme look fine. No idea about the main php file.

2020-12-20 05:41 UTC, bahiirwa commented
@simplycomputing Could you test this branch in a CP install to see if all works well? User experience should be the same as before. Nothing has fundamentally changed apart from having a txt file on server. 

Yah, you might have to make new snippets as the post type name has changed. Or you can migrate the old posts using a plugin like post type switcher by JJJ

2020-12-20 08:12 UTC, simplycomputing commented
The shortcode isn't working for me. Just shows the shortcode.

2020-12-20 08:19 UTC, simplycomputing commented
Ah, OK. You changed the shortcode text. Working now.

2020-12-20 08:23 UTC, simplycomputing commented
"View Raw" gives a 404. Also if I go to the code snippet page and try "view page" then it gives a 404 as well.

2020-12-20 14:53 UTC, bahiirwa commented
Have you tried to save the settings as postname again on CP. post type things. 😄

2020-12-20 16:03 UTC, timbocode requested changes
This is good work!

I've not tested this exhaustively yet but a couple of quick comments:

1. It should be made obvious what the shortcode format is somewhere in admin, either in the code list page or on the code edit page. Or both.
2. I got a "page not found" when clicking on the "View Raw" button
3. When clicking on the "Copy to Clipboard" button, if the code contains special characters (such as `\n`), it does not paste correctly. For example:

**Original (copied) code:**
```
$notices = (array) preg_split( '~[\r\n]+~', trim( $matches[2] ) );
```

**Result when pasted:**
```
$notices = (array) preg_split( '~[
]+~', trim( $matches[2] ) );
```

and

**Original**

```
$upgrade_notice .= preg_replace( '~\[([^\]]*)\]\(([^\)]*)\)~', '<a href="${2}">${1}</a>', $line );
```

**Pasted**

```
$upgrade_notice .= preg_replace( '~[([^]]*)](([^)]*))~', '<a href="2">1</a>', $line );
```

The code seems to display fine. It's just when it's copied to the clipboard.

4. Can we stick with the original proposed name of "**Classic Code Snippets**" everywhere please ("Code Snippets" is fine for the admin menu). 

Other than that, it's looking really good. It will be a nice addition to the plugin ecosystem, so well done both.

2020-12-20 18:32 UTC, bahiirwa commented
Thanks for the review. Will go test and extract the noted issues in depth.

For clarity
> It should be made obvious what the shortcode format is somewhere in admin, either in the code list page or on the code edit page. Or both.

Do you mean something like this in the snippet edit page? (I am borrowing from Gravity forms)

<img src="https://resources.gravitypdf.com/uploads/2015/10/shortcode-sample.png">

If yes, that would a new feature request to work on.

2020-12-20 20:03 UTC, timbocode commented
Yes, something like the Gravity PDF doodah would be great. New feature request is fine but in the meantime, it would be good to add "example usage" to the plugin description, like so:

![ccs-usage](https://user-images.githubusercontent.com/4199514/102723211-68a98a80-42fe-11eb-9efc-c3602e078272.jpg)

2020-12-20 20:59 UTC, simplycomputing commented
Re-saving permalinks fixed the issue (forgot about the need for that).

All looks good!

2020-12-21 13:16 UTC, timbocode commented
Just to confirm, resaving permalinks sorted the 404 for me too. And the raw code displayed fine.

2020-12-22 14:55 UTC, bahiirwa commented
I have looked into the other issues and resolved them.

> When clicking on the "Copy to Clipboard" button, if the code contains special characters (such as \n), it does not paste correctly.

Seem this issue is with the JS we are using. I will research further on this.

2020-12-24 22:15 UTC, simplycomputing commented
I am just testing this again. Is is true that the main file is still called classic-display-code.php?

Shouldn't this be changed to classic-code-snippets.php?

2020-12-25 13:28 UTC, timbocode commented
There's some work here @bahiirwa. 

Just to confirm @simplycomputing's comment about the main file. Yes, it should be called `classic-code-snippets.php` rather than `classic-display-code.php`.

Also need to look into the conflicting files. It might be happening because an earlier commit contained these two files (`form.php` and `sc-display-code.php`) but now neither of them exist in this latest commit. I'll try and look into it v soon.

2020-12-26 04:03 UTC, simplycomputing commented
Re formatting issues. I've just remembered that when I first set this up it did some weird things on the occasional snippet. I eventually worked out that it sort of auto-detects the type of code and formats accordingly. So mostly it correctly worked out it was php, but sometimes it would think it was something else. To fix this I set it to treat everything as php (because all of the CC snippets were php). You can see in the main file there is this:

```
return '
	<pre>
		<code class="language-php">' . $myVar  . '</code>
	</pre>
	<div>
```
That class may be causing issues and should be removed.

2020-12-26 17:43 UTC, bahiirwa commented
My thoughts as well @simplycomputing. I will rebase and make a commit before review.

2020-12-26 20:54 UTC, simplycomputing commented
Trouble is, if I use it _without_ that class then the problem I was experiencing will return. I guess ideally it would have a selector so you could choose what language you want it to format to. 

That might be a possible enhancement for later.

2020-12-27 09:05 UTC, bahiirwa commented
This can be reviewed as it. I have pulled out a number of issues I saw testing with the copy to clipboard implementation.

2020-12-28 11:12 UTC, timbocode requested changes
Looking good. Just a couple of additional observations:

1. The file `form.php` seems to be superfluous and should probably be removed.
2. When creating a new code snippet, I get the following PHP notice:

```
NOTICE: .../wp-content/plugins/classic-code-snippets/classic-code-snippets.php:128 - Undefined index: ccs_code_snippet
```

It's definitely getting there.

2020-12-28 21:36 UTC, bahiirwa commented on classic-code-snippets.php
> +}
I agree @timbocode. This particular piece removes the `form.php` file.

I think it was done to separate the concerns of the technologies.

2020-12-28 21:38 UTC, bahiirwa commented on classic-code-snippets.php
> +		<textarea id="ccs_code_snippet" rows="20" class="widefat" name="ccs_code_snippet"><?php echo esc_attr( $ccs_code_snippet ); ?></textarea>
My bad. I see that I left both input fields with the same name. That conflicts with the metadata as it is in a singular form. I will make the html ammends.

2020-12-30 17:13 UTC, bahiirwa commented on classic-code-snippets.php
> +		<textarea id="ccs_code_snippet" rows="20" class="widefat" name="ccs_code_snippet"><?php echo esc_attr( $ccs_code_snippet ); ?></textarea>
Fixed

2021-01-02 14:48 UTC, timbocode commented
I seem to have broken it. My bad.

The shortcode no longer works for me. It just displays `[ccs_snippet id=xxx]` although I've also noticed that the shortcode name appears to have changed to `css_snippets` (with an 's' at the end) - which I've also tried.

I'm also still getting `PHP Notice:  Undefined index: ccs_code_snippet in .../classic-code-snippets/classic-code-snippets.php on line 128` when creating a new code post and also when creating a new, ordinary post.

I've tried on two separate sites (different themes etc.).

2021-01-03 11:54 UTC, bahiirwa commented
> The shortcode no longer works for me. It just displays [ccs_snippet id=xxx] although I've also noticed that the shortcode name appears to have changed to css_snippets (with an 's' at the end) - which I've also tried.

I should be tried on the stake. Added a fix.

I have tried to follow these steps to recreate your issue.
1. Installed fresh CP and turned on `WP_DEBUG`in `wp-config.php` etc.
2. Pull plugin from repo.
3. `git co rename` branch
4. Activate plugin.
5. Create new snippet
6. Add snippet to page.
7. View page. I do not have issue raised.

2021-01-03 12:08 UTC, bahiirwa commented
>I'm also still getting PHP Notice: Undefined index: ccs_code_snippet in .../classic-code-snippets/classic-code-snippets.php on line 128 when creating a new code post and also when creating a new, ordinary post.

However, with the last commit, I have rewritten the lines in 128 in the old way. Let me know if this is necessary and fixes the issue.

2021-01-03 14:13 UTC, timbocode approved these changes
All good now Laurence. Your fixes have worked.

The shortcode is working fine and I no longer get the PHP error.

So, all good to go now.

2021-01-03 14:34 UTC, merged